[package]
name = "good-boy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tokio = { version = "1.26.0", features = ["full"] }

regex = "1.7.2"
xml-rs = "0.8.4"
url = "2.3.1"
reqwest = "0.11.15"